export const MONSTERS = {
  AESTHER_ASHBLADE: 'Aesther Ashblade',
  AESTHER_SCOUT: 'Aesther Scout',
  ANCIENT_ARTILLERY: 'Ancient Artillery',
  BANDIT_ARCHER: 'Bandit Archer',
  BANDIT_GUARD: 'Bandit Guard',
  BLACK_IMP: 'Black Imp',
  CAVE_BEAR: 'Cave Bear',
  CITY_ARCHER: 'City Archer',
  CITY_GUARD: 'City Guard',
  CULTIST: 'Cultist',
  DEEP_TERROR: 'Deep Terror',
  EARTH_DEMON: 'Earth Demon',
  FLAME_DEMON: 'Flame Demon',
  FROST_DEMON: 'Frost Demon',
  FOREST_IMP: 'Forest Imp',
  GIANT_VIPER: 'Giant Viper',
  HARROWER_INFESTER: 'Harrower Infester',
  HOUND: 'Hound',
  INOX_ARCHER: 'Inox Archer',
  INOX_GUARD: 'Inox Guard',
  INOX_SHAMAN: 'Inox Shaman',
  LIVING_BONES: 'Living Bones',
  LIVING_CORPSE: 'Living Corpse',
  LIVING_SPIRIT: 'Living Spirit',
  LURKER: 'Lurker',
  OOZE: 'Ooze',
  NIGHT_DEMON: 'Night Demon',
  RENDING_DRAKE: 'Rending Drake',
  SAVVAS_ICESTORM: 'Savvas Icestorm',
  SAVVAS_LAVAFLOW: 'Savvas Lavaflow',
  SPITTING_DRAKE: 'Spitting Drake',
  STONE_GOLEM: 'Stone Golem',
  SUN_DEMON: 'Sun Demon',
  VALRATH_SAVAGE: 'Valrath Savage',
  VALRATH_TRACKER: 'Valrath Tracker',
  VERMLING_SCOUT: 'Vermling Scout',
  VERMLING_SHAMAN: 'Vermling Shaman',
  WIND_DEMON: 'Wind Demon',
};

export const BOSSES = {
  BANDIT_COMMANDER: 'Bandit Commander',
  BETRAYER: 'The Betrayer',
  CAPTAIN: 'Captain of the Guard',
  COLORLESS: 'The Colorless',
  DARK_RIDER: 'Dark Rider',
  DRAKE: 'Elder Drake',
  GLOOM: 'The Gloom',
  HUMAN_COMMANDER: 'Human Commander',
  INOX_BODYGUARD: 'Inox Bodyguard',
  JEKSERAH: 'Jekserah',
  MANIFESTATION: 'Manifestation of Corruption',
  OVERSEER: 'Merciless Overseer',
  PRIME_DEMON: 'Prime Demon',
  SIGHTLESS_EYE: 'The Sightless Eye',
  VALRATH_COMMANDER: 'Valrath Commander',
  WINGED_HORROR: 'Winged Horror',

  RAIDER_KING: 'Raider King', // Special representation of the Bandit Commander
};
