export const JEKSERAH = {
  standeeCount: 1,
  isBoss: true,
  level: [
    {
      level: 0,
      health: '6xC',
      move: 2,
      attack: 2,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 1,
      health: '7xC',
      move: 2,
      attack: 3,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 2,
      health: '9xC',
      move: 3,
      attack: 3,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 3,
      health: '12xC',
      move: 4,
      attack: 4,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 4,
      health: '13xC',
      move: 4,
      attack: 5,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 5,
      health: '15xC',
      move: 5,
      attack: 5,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 6,
      health: '18xC',
      move: 5,
      attack: 5,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
    {
      level: 7,
      health: '22xC',
      move: 5,
      attack: 5,
      range: 0,
      special1: [
        'Summon Living Bones',
        '%attack% -1, Target all adjacent enemies',
      ],
      special2: [
        'Summon Living Corpse',
        '%move% -1',
        '%attack% +2',
      ],
      immunities: [
        '%disarm%',
        '%wound%',
        '%curse%',
        '%stun%',
      ],
      notes: '',
    },
  ],
};
